name: base_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  envied: ^0.3.0+3

  get_it: ^7.6.4

  flutter_bloc: ^8.1.3

  dio: ^5.3.2

  logger: ^2.0.1

  flutter_screenutil: ^5.9.0

  go_router: ^10.1.2

  shared_preferences: ^2.2.1

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6

  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true